name: mac-build

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: select xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.1.app && /usr/bin/xcodebuild -version
    - name: build
      working-directory: build/mac
      run: xcodebuild -project clap-plugin.xcodeproj
    - uses: actions/upload-artifact@v4
      with:
        name: clap-example.clap
        path: build/mac/build/Release/clap-example.clap
