name: win-build

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: select msbuild
      uses: microsoft/setup-msbuild@v1.1
    - name: build
      working-directory: build/win
      run: MSBuild /m /p:PlatformToolset=v142 /p:Configuration=Release
    - uses: actions/upload-artifact@v2
      with:
        name: clap-example.clap
        path: D:\a\clap-imgui\clap-imgui\build\win\Release\clap-plugin.clap
